version: '3.4'

services:
  db:
    image: postgres:13-alpine
    ports:
      - 5432:5432
    restart: always
    environment:
      - POSTGRES_DB=sanctions
      - POSTGRES_USER=sanctions
      - POSTGRES_PASSWORD=are-fun

  test-db:
    image: postgres:13-alpine
    ports:
      - 5433:5432
    restart: always
    environment:
      - POSTGRES_DB=sanctions
      - POSTGRES_USER=sanctions
      - POSTGRES_PASSWORD=are-fun

  api:
    build:
      context: ./
      target: api-base
    entrypoint: [ 'go' ]
    command: [ 'run', 'main.go' ]
    stdin_open: true
    tty: true
    volumes:
      - ./:/go/src/github.com/Sigma-Ratings/sigma-code-challenges/
    depends_on:
      - db
      - test-db
    ports:
      - 80:80

  test:
    build:
      context: smoketest
      dockerfile: Dockerfile
    links:
      - api
    environment:
      - API=api:80
    command:
      - ./run.sh
    volumes:
      - ./smoketest:/smoketest